kumuluzee:
  name: code-grades
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/GradeMetadataPS
      connection-url: jdbc:postgresql://localhost:5436/code-grades
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
