kumuluzee:
  name: code-grades
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/GradeMetadataPS
      connection-url: jdbc:postgresql://localhost:5436/code-grades
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  streaming:
    kafka:
      consumer:
        bootstrap-servers: moped-01.srvs.cloudkafka.com:9094
        group-id: newer
        enable-auto-commit: true
        auto-commit-interval-ms: 1000
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
